### PR TITLE
Add an env variable to set the RyukContainer port binding

### PR DESCRIPTION
**Pull request by srollinet**
Fixes https://github.com/isen-ng/testcontainers-dotnet/issues/58

### CODE REVIEW

**Comment by srollinet** [comment]
This is a proposal to fix the issue with Ryuk on Windows + WSL (https://github.com/isen-ng/testcontainers-dotnet/issues/58)

Other possibilities
- Opt this feature in (for example with an env variable, or another mechanism)
- Give the port explicitly (same, with an env variable or another mechanism)
- Only add the binding if OS is Windows

**Comment by srollinet** [comment]
And maybe it can also be extended to db containers. As any port randomly generated by docker could be problematic.

**Comment by isen-ng** [comment]
There is a problem with `FreePortHelper.GetFreePort()` (or any other free port detector) making it unreliable for production use.

This is the problem:

1. free port getters gets a free port by trying to open a (tcp/udp/socket) connection to itself using port `0`
2. this allows the OS to assign a free port automatically
3. after getting the port number, the connection is closed, releasing the port
4. the free port is passed to the next chunk of code, to be used

Between 3 and 4, the port that was detected as free could have been used by the OS for something else. That's why the free port helper only exists in test code and not in production code.

**Comment by isen-ng** [comment]
It would have been a better solution to allow assigning a port to ryuk using environment variables.
if a user assign a port below `32000` (OS' dynamic port range), there will be no dynamic collisions by the OS.

---

On the other hand, travis no longer has a free tier, even for open source it seems. I'll need to migrate the CI/CD to github actions this weekend

**Comment by srollinet** [comment]
Yes, there is a race condition, I don't know how likely it is to happen.
I'm ok with the env variable solution, so it is the user responsibility to provide an open port.

The PR is updated, and if you're ok with this solution I will squash the changes and update the documentation / unit tests

**Comment by isen-ng** [comment]
Yeah, I think this solution is better.
If you don't mind waiting, let me fix the CI this weekend and we can merge and release this

**Comment by srollinet** [comment]
I added the new env. variable in the readme and squashed the commits to make it cleaner
I don't know if you want a test for this env. variable. As everything is static, I don't think it is possible to add a new test without affecting the existing ones. (Unless it is executed in its own test run)

**Comment by isen-ng** [comment]
I think it's okay without tests.
Running tests with fixed ports are potentially flaky and flaky tests are annoying.

Thank you for the PR, I'm going to merge this and make a release

**Comment by isen-ng** [comment]
@srollinet This has been released in v1.5.1.
You should be able to pull from nuget after a few hours (of them indexing it)

**Pull request merged**
